[package]
name = "uds-rs"
version = "0.3.1"
edition = "2024"
authors = [
    "Jakub Jíra <jakub.jira@protonmail.com>",
    "Willem Roovers <willemroovers@protonmail.com>",
]
license-file = "LICENCE"
description = "A asynchronous library implementing UDS protocol over CAN used for automotive diagnostic, standardized by ISO 14229-1:2013."
homepage = "https://github.com/japawBlob/uds-rs"
repository = "https://github.com/japawBlob/uds-rs"
readme = "README.md"
keywords = ["async", "uds", "iso-14229-1", "can"]
categories = ["network-programming", "os::linux-apis", "asynchronous"]

[badges]
maintenance = { status = "actively-developed" }

[dev-dependencies]
env_logger = "0.11.11"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
futures-util = "0.3.33"
futures-timer = "3.0.4"
futures = "0.3.33"
rand = "0.10.2"
bitflags = "2.13.1"
embedded-can = "0.4"
libc = "0.2.189"
nix = "0.31.3"
thiserror = "2.0.19"
mio = { version = "1.2.2", features = ["os-ext"] }
num_enum = "0.7.6"
log = "0.4.33"
tokio-socketcan-isotp = "0.2"
